# Code of Conduct {#code}

**Does the lab have a code of conduct to inlude here? Do we need to make one?**

## Short version

**Give a TL;DR of the code of conduct here**

## Longer version

**Give link to code of conduct or paste whole here**

### Reporting

**Give summary of reporting procedures for UM & NOAA and add relative links**


__Confidentiality:__  
**Give Chris's similar statement & statements for lab**

Please remember that by way of his position at the university, Dr. Fay is a mandated reporter under Title IX. This means that he is not allowed to keep matters falling under Title IX confidential, and is required to disclose these incidents to the administration. You are welcome to discuss matters with Dr. Fay, but please keep this in mind when doing so. Gavin will do his best to remind you of his responsibilities at the start of conversations anticipated to relate to these topics. If you would prefer to discuss incidents of harassment that fall under Title IX with a confidential source, you can contact [David Gomes, UMass Dartmouth Director of Diversity and Inclusion](mailto:david.gomes.eeo@umassd.edu).  

This code of conduct applies to Fay lab spaces, but if you are being harassed by a member of the Fay lab or another member of the SMAST community outside our spaces, we still want to know about it. We will take all good-faith reports of harassment by Fay lab members seriously. This includes harassment outside our spaces and harassment that took place at any point in time. The abuse team reserves the right to exclude people from the Fay lab based on their past behavior, including behavior outside Fay lab spaces and behavior towards people who are not in the Fay lab. The [University Counseling Center](http://www.umassd.edu/counseling/) provides a range of services to help students develop improved coping skills to address emotional, interpersonal and academic concerns.  

To protect our team members from abuse and burnout, we reserve the right to reject any report we believe to have been made in bad faith. Reports intended to silence legitimate criticism may be deleted without response.  

The above caveats noted, we will respect confidentiality requests for the purpose of protecting victims of abuse when possible. At our discretion, we may publicly name a person about whom we’ve received harassment complaints, or privately warn third parties about them, if we believe that doing so will increase the safety of the Fay lab members or the general public. We will not name harassment victims without their affirmative consent.  

### Consequences

**Add consequences of certain behaviors here**

