# Onboarding {#onboarding}

Welcome to the Ecosystem Assessment Lab!

## Adaptable welcome orientation email
Our lab group and Ocean Chemistry and Ecosystems division director, Dr. Chris Kelble works onsite in the lab in Miami and is also available via email- cc'd here. He will communicate regarding your assigned office space once your NOAA security clearance is complete. 

One of your tasks in this role will be processing and analyzing chlorophyll samples. Please reach out to Ian Smith, our lab group's lead on fieldwork operations, cc'd here, to schedule time to train on this. 

I'm also connecting you to one of our research associates, Alex Fine, another lab senior research associate, who may also have some data prep/QA QC for you to help with. She may also have some fieldwork prep she needs help on.

Once your NOAA security clearance comes through, you'll also have to do the NOAA AOML onboarding. Emy Rodriguez, cc'd here from our Ocean Chemistry and Ecosystems Division, will help you with that. She will arrange meet and greets with AOML leadership. She will also provide guidance on obtaining a NOAA AOMl key card to access the 

Please reach out to Christian Saiz, AOML's CIMAS liaison cc'd here, for orientation information on being a cooperative institute employee.

Rachel Cohn, our lab group IT person, will help get you set up with a computer and NOAA email once your security clearance comes through. NOAA email uses gmail and the Google suite, so be sure to update your calendar and check it every day for meetings, invites, field calendars, etc. We have weekly lab meetings via Google Meets, and I'll send you an invite to this email address for now.

You'll also have to take a few training modules to get checked out to drive our lab government vehicles and vessels and complete CPR, oxygen and AED training, and our NOAA corps officer and VOC, Timothy Holland will help you with that. He is also our contact to register and begin the NOAA Small Boat Component Course, which is needed in order to become a boat operator. 

In the meantime, please be sure to communicate with the RSMAS dive office to be sure you are up to date and ready to log dives as a UM/scientific diver, and have copies of all of your certifications (MOCC, first aid, CPR, AED, O2) ready to share with Tim Holland as well. Also make sure that your UM ID card is working and set up to give you access to the gate as well as the dock gate.

I am also attaching a report and a paper on some of our fieldwork projects ( "seatrout" and red tide) for you to familiarize yourself with, as well as this lab group page https://www.aoml.noaa.gov/so-flo-ecosystem-restoration/. 

Here are some resources to help you get settled into the Lab.  

**ADD RESOURCES HERE**

## NOAA & UM Resources (Placeholder)



## Facilities

**ADD NECESSARY INFO ABOUT FACILITIES HERE**

### Office space


### Key card building & room access


### Parking and transportation: 

