# Expectations {#expectations}

**General lab expectations**  

## Working hours




## Email

**Put in our own words or update**
In the lab, we communicate via email. You should therefore check your email at least once a day during the normal work week. We also make use of Google Docs and issues on GitHub to record institutional knowledge and hold conversations regarding research tasks. Note that being available does not mean that you are available 24/7 - this is not expected. Do not expect responses to emails after regular business hours on weekdays, or on weekends. However, because we recognize that lab members should be able to create a working schedule that is right for them, lab members should not be penalized for sending communication during these times.   


## Attendance at regularly scheduled events
**Are there things Chris would like to encourage us to be at**
Attendance is expected at:


## Outreach
**What to share & how to share it**

## Expectations for the PI

**List of what Chris would like to assist with**


**Add expectations for different levels of staff in the lab**
