project: 
  type: book
  output-dir: _book
  
book:
  title: "Ecosystem Assessment Lab Manual"
  author: "Chris Kelble"
  date: last-modified 
  description: "This is the lab manual for the Ecosystem Assessment Laboratory in NOAA's Atlantic Oceanographic and Meteorological Laboratory" 
  
  page-footer:
    left: |
      <a href="http://www.smast.umassd.edu/lab_fay/">The Fay lab</a>
    right: |
      This book was built with <a href="https://quarto.org/">Quarto</a>.
  site-url: https://ecosystem-assessment-lab.github.io/lab-manual/
  repo-url: https://github.com/Ecosystem-Assessment-Lab/lab-manual
  repo-actions: [edit,issue]

  chapters: 
    - index.qmd
    - 01-intro-how-we-work.qmd
    - 02-lab-culture-philosophy.qmd
    - 03-code-of-conduct.qmd
    - 04-onboarding.qmd
    - 05-expectations.qmd
    - 06-offboarding.qmd
    - 07-funding.qmd
    - 08-communication.qmd
    - 09-academics.qmd
    - 10-courses.qmd
    - 11-computing.qmd
    - 12-umassd-resources.qmd
#    - 13-smast-resources.qmd
#    - 14-other-faylab-resources.qmd  



