# Welcome!


<br> This is the lab manual for the Ecosystem Assessment Laboratory at NOAA's Atlantic Oceanographic and Meteorological Laboratory\

The goal of our research is to develop ecosystem assessments and related products to improve the management of marine and coastal resources and ecosystems along the Atlantic Ocean and Gulf of Mexico. We: 1)collect observations, 2) develop ecosystem assessment frameworks, 3) develop indicators, 4) develop and run ecosystem models, and 5) conduct statistical analyses.

This lab manual resource is intended to provide an overview for lab members and others about how we do our work, and our expectations for our team. It is also a space to document institutional knowledge and for important information about procedures and available resources. If you have any suggestions, please email chris.kelble@noaa.gov or make a pull request.

This lab manual was based upon the lab manual developed by the Fay Lab (). It was undertaken as part of our OpenScapes training.

<br>

